/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "ahb_master.v:16.1-142.10" *)
module ahb_master(HCLK, HRESETn, HADDR, HWRITE, HSIZE, HBURST, HTRANS, HPROT, HWDATA, HRDATA, HREADY, HRESP, start, addr_in, wr);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire [1:0] _014_;
  wire _015_;
  wire _016_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [5:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [5:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [1:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [5:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [5:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [1:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [1:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [63:0] _026_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [63:0] _027_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [31:0] _028_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [31:0] _029_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "31" *)
  wire [31:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _032_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:117.39-117.55|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [2:0] _033_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:117.39-117.55|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:117.39-117.55|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [2:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:113.25-113.41|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [2:0] _036_;
  (* force_downto = 32'd1 *)
  (* src = "ahb_master.v:113.25-113.41|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [2:0] _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _041_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _042_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _043_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _044_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _045_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _046_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _047_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _048_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _049_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _050_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _051_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _052_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _053_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _054_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _055_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _056_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _057_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _058_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _059_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _060_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _061_;
  (* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _062_;
  (* src = "ahb_master.v:27.24-27.29" *)
  output [31:0] HADDR;
  reg [31:0] HADDR;
  (* src = "ahb_master.v:30.24-30.30" *)
  output [2:0] HBURST;
  wire [2:0] HBURST;
  (* src = "ahb_master.v:21.24-21.28" *)
  input HCLK;
  wire HCLK;
  (* src = "ahb_master.v:32.24-32.29" *)
  output [3:0] HPROT;
  wire [3:0] HPROT;
  (* src = "ahb_master.v:38.24-38.30" *)
  input [31:0] HRDATA;
  wire [31:0] HRDATA;
  (* src = "ahb_master.v:39.24-39.30" *)
  input HREADY;
  wire HREADY;
  (* src = "ahb_master.v:22.24-22.31" *)
  input HRESETn;
  wire HRESETn;
  (* src = "ahb_master.v:40.24-40.29" *)
  input HRESP;
  wire HRESP;
  (* src = "ahb_master.v:29.24-29.29" *)
  output [2:0] HSIZE;
  wire [2:0] HSIZE;
  (* src = "ahb_master.v:31.24-31.30" *)
  output [1:0] HTRANS;
  reg [1:0] HTRANS;
  (* src = "ahb_master.v:33.24-33.30" *)
  output [31:0] HWDATA;
  wire [31:0] HWDATA;
  (* src = "ahb_master.v:28.24-28.30" *)
  output HWRITE;
  reg HWRITE;
  (* src = "ahb_master.v:42.24-42.31" *)
  input [31:0] addr_in;
  wire [31:0] addr_in;
  (* src = "ahb_master.v:58.15-58.24" *)
  reg [2:0] burst_cnt;
  (* src = "ahb_master.v:41.24-41.29" *)
  input start;
  wire start;
  (* src = "ahb_master.v:43.24-43.26" *)
  input wr;
  wire wr;
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HWRITE <= 1'h0;
    else if (_004_) HWRITE <= wr;
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HTRANS[0] <= 1'h0;
    else if (_006_) HTRANS[0] <= _024_[0];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HTRANS[1] <= 1'h0;
    else if (_006_) HTRANS[1] <= _024_[1];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) burst_cnt[0] <= 1'h0;
    else if (_007_) burst_cnt[0] <= _020_[0];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) burst_cnt[1] <= 1'h0;
    else if (_007_) burst_cnt[1] <= _020_[1];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) burst_cnt[2] <= 1'h0;
    else if (_007_) burst_cnt[2] <= _020_[2];
  reg \HBURST_reg[0] ;
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) \HBURST_reg[0]  <= 1'h0;
    else if (_005_) \HBURST_reg[0]  <= 1'h1;
  assign HBURST[0] = \HBURST_reg[0] ;
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[0] <= 1'h0;
    else if (_008_) HADDR[0] <= _028_[0];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[1] <= 1'h0;
    else if (_008_) HADDR[1] <= _028_[1];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[2] <= 1'h0;
    else if (_008_) HADDR[2] <= _028_[2];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[3] <= 1'h0;
    else if (_008_) HADDR[3] <= _028_[3];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[4] <= 1'h0;
    else if (_008_) HADDR[4] <= _028_[4];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[5] <= 1'h0;
    else if (_008_) HADDR[5] <= _028_[5];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[6] <= 1'h0;
    else if (_008_) HADDR[6] <= _028_[6];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[7] <= 1'h0;
    else if (_008_) HADDR[7] <= _028_[7];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[8] <= 1'h0;
    else if (_008_) HADDR[8] <= _028_[8];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[9] <= 1'h0;
    else if (_008_) HADDR[9] <= _028_[9];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[10] <= 1'h0;
    else if (_008_) HADDR[10] <= _028_[10];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[11] <= 1'h0;
    else if (_008_) HADDR[11] <= _028_[11];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[12] <= 1'h0;
    else if (_008_) HADDR[12] <= _028_[12];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[13] <= 1'h0;
    else if (_008_) HADDR[13] <= _028_[13];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[14] <= 1'h0;
    else if (_008_) HADDR[14] <= _028_[14];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[15] <= 1'h0;
    else if (_008_) HADDR[15] <= _028_[15];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[16] <= 1'h0;
    else if (_008_) HADDR[16] <= _028_[16];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[17] <= 1'h0;
    else if (_008_) HADDR[17] <= _028_[17];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[18] <= 1'h0;
    else if (_008_) HADDR[18] <= _028_[18];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[19] <= 1'h0;
    else if (_008_) HADDR[19] <= _028_[19];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[20] <= 1'h0;
    else if (_008_) HADDR[20] <= _028_[20];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[21] <= 1'h0;
    else if (_008_) HADDR[21] <= _028_[21];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[22] <= 1'h0;
    else if (_008_) HADDR[22] <= _028_[22];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[23] <= 1'h0;
    else if (_008_) HADDR[23] <= _028_[23];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[24] <= 1'h0;
    else if (_008_) HADDR[24] <= _028_[24];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[25] <= 1'h0;
    else if (_008_) HADDR[25] <= _028_[25];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[26] <= 1'h0;
    else if (_008_) HADDR[26] <= _028_[26];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[27] <= 1'h0;
    else if (_008_) HADDR[27] <= _028_[27];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[28] <= 1'h0;
    else if (_008_) HADDR[28] <= _028_[28];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[29] <= 1'h0;
    else if (_008_) HADDR[29] <= _028_[29];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[30] <= 1'h0;
    else if (_008_) HADDR[30] <= _028_[30];
  (* src = "ahb_master.v:63.5-140.8" *)
  always @(posedge HCLK, negedge HRESETn)
    if (!HRESETn) HADDR[31] <= 1'h0;
    else if (_008_) HADDR[31] <= _028_[31];
  assign _009_ = ~HTRANS[0];
  assign _010_ = ~HTRANS[1];
  assign _013_ = HREADY & start;
  assign _004_ = _013_ & _023_[2];
  assign _005_ = HREADY & _019_[1];
  assign _016_ = HTRANS[0] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20" *)  _010_;
  assign _012_ = _009_ |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20" *)  _010_;
  assign _000_ = start | _011_;
  assign _007_ = HREADY & _001_;
  assign _002_ = _021_[1] | _012_;
  assign _003_ = _019_[0] | _023_[2];
  assign _006_ = HREADY & _000_;
  assign _014_[1] = _002_ & _003_;
  assign _008_ = _006_ & _014_[1];
  assign _025_[1] = _015_ |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _022_[5];
  assign _015_ = _022_[1] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _019_[1];
  assign _025_[0] = _015_ |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _022_[4];
  assign _001_ = _019_[0] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _019_[1];
  assign _041_ = _001_ |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _023_[2];
  assign _029_[31] = _027_[31] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[63];
  assign _029_[30] = _027_[30] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[62];
  assign _029_[29] = _027_[29] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[61];
  assign _029_[28] = _027_[28] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[60];
  assign _029_[27] = _027_[27] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[59];
  assign _029_[26] = _027_[26] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[58];
  assign _029_[25] = _027_[25] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[57];
  assign _029_[24] = _027_[24] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[56];
  assign _029_[23] = _027_[23] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[55];
  assign _029_[22] = _027_[22] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[54];
  assign _029_[21] = _027_[21] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[53];
  assign _029_[20] = _027_[20] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[52];
  assign _029_[19] = _027_[19] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[51];
  assign _029_[18] = _027_[18] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[50];
  assign _029_[17] = _027_[17] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[49];
  assign _029_[16] = _027_[16] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[48];
  assign _029_[15] = _027_[15] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[47];
  assign _029_[14] = _027_[14] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[46];
  assign _029_[13] = _027_[13] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[45];
  assign _029_[12] = _027_[12] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[44];
  assign _029_[11] = _027_[11] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[43];
  assign _029_[10] = _027_[10] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[42];
  assign _029_[9] = _027_[9] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[41];
  assign _029_[8] = _027_[8] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[40];
  assign _029_[7] = _027_[7] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[39];
  assign _029_[6] = _027_[6] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[38];
  assign _029_[5] = _027_[5] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[37];
  assign _029_[4] = _027_[4] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[36];
  assign _029_[3] = _027_[3] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[35];
  assign _029_[2] = _027_[2] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[34];
  assign _029_[1] = _027_[1] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[33];
  assign _029_[0] = _027_[0] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _027_[32];
  assign _011_ = HTRANS[0] |(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20" *)  HTRANS[1];
  assign _019_[1] = ~(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20" *) _016_;
  assign _019_[0] = ~(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20" *) _012_;
  assign _023_[2] = ~(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20" *) _011_;
  assign _017_[0] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'h0 : _034_[0];
  assign _017_[1] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'h0 : _035_[1];
  assign _017_[2] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'h0 : _035_[2];
  assign _021_[1] = ~(* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) _040_;
  assign _021_[4] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) 1'h0 : 1'hx;
  assign _021_[5] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) 1'h1 : 1'hx;
  assign _026_[0] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : HADDR[0];
  assign _026_[1] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : HADDR[1];
  assign _026_[2] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _031_[2];
  assign _026_[3] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[3];
  assign _026_[4] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[4];
  assign _026_[5] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[5];
  assign _026_[6] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[6];
  assign _026_[7] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[7];
  assign _026_[8] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[8];
  assign _026_[9] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[9];
  assign _026_[10] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[10];
  assign _026_[11] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[11];
  assign _026_[12] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[12];
  assign _026_[13] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[13];
  assign _026_[14] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[14];
  assign _026_[15] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[15];
  assign _026_[16] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[16];
  assign _026_[17] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[17];
  assign _026_[18] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[18];
  assign _026_[19] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[19];
  assign _026_[20] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[20];
  assign _026_[21] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[21];
  assign _026_[22] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[22];
  assign _026_[23] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[23];
  assign _026_[24] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[24];
  assign _026_[25] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[25];
  assign _026_[26] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[26];
  assign _026_[27] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[27];
  assign _026_[28] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[28];
  assign _026_[29] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[29];
  assign _026_[30] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[30];
  assign _026_[31] = _040_ ? (* src = "ahb_master.v:113.25-113.41|ahb_master.v:113.21-125.24" *) 1'hx : _032_[31];
  assign _026_[32] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[0] : 1'hx;
  assign _026_[33] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[1] : 1'hx;
  assign _026_[34] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[2] : 1'hx;
  assign _026_[35] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[3] : 1'hx;
  assign _026_[36] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[4] : 1'hx;
  assign _026_[37] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[5] : 1'hx;
  assign _026_[38] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[6] : 1'hx;
  assign _026_[39] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[7] : 1'hx;
  assign _026_[40] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[8] : 1'hx;
  assign _026_[41] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[9] : 1'hx;
  assign _026_[42] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[10] : 1'hx;
  assign _026_[43] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[11] : 1'hx;
  assign _026_[44] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[12] : 1'hx;
  assign _026_[45] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[13] : 1'hx;
  assign _026_[46] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[14] : 1'hx;
  assign _026_[47] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[15] : 1'hx;
  assign _026_[48] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[16] : 1'hx;
  assign _026_[49] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[17] : 1'hx;
  assign _026_[50] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[18] : 1'hx;
  assign _026_[51] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[19] : 1'hx;
  assign _026_[52] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[20] : 1'hx;
  assign _026_[53] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[21] : 1'hx;
  assign _026_[54] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[22] : 1'hx;
  assign _026_[55] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[23] : 1'hx;
  assign _026_[56] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[24] : 1'hx;
  assign _026_[57] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[25] : 1'hx;
  assign _026_[58] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[26] : 1'hx;
  assign _026_[59] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[27] : 1'hx;
  assign _026_[60] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[28] : 1'hx;
  assign _026_[61] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[29] : 1'hx;
  assign _026_[62] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[30] : 1'hx;
  assign _026_[63] = start ? (* src = "ahb_master.v:92.8-92.13|ahb_master.v:92.5-96.8" *) addr_in[31] : 1'hx;
  assign _020_[0] = _001_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _018_[0] : 1'hx;
  assign _020_[1] = _001_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _018_[1] : 1'hx;
  assign _020_[2] = _001_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _018_[2] : 1'hx;
  assign _024_[0] = _041_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _025_[0] : 1'h0;
  assign _024_[1] = _041_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _025_[1] : 1'h0;
  assign _028_[0] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[0] : 1'hx;
  assign _028_[1] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[1] : 1'hx;
  assign _028_[2] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[2] : 1'hx;
  assign _028_[3] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[3] : 1'hx;
  assign _028_[4] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[4] : 1'hx;
  assign _028_[5] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[5] : 1'hx;
  assign _028_[6] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[6] : 1'hx;
  assign _028_[7] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[7] : 1'hx;
  assign _028_[8] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[8] : 1'hx;
  assign _028_[9] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[9] : 1'hx;
  assign _028_[10] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[10] : 1'hx;
  assign _028_[11] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[11] : 1'hx;
  assign _028_[12] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[12] : 1'hx;
  assign _028_[13] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[13] : 1'hx;
  assign _028_[14] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[14] : 1'hx;
  assign _028_[15] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[15] : 1'hx;
  assign _028_[16] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[16] : 1'hx;
  assign _028_[17] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[17] : 1'hx;
  assign _028_[18] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[18] : 1'hx;
  assign _028_[19] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[19] : 1'hx;
  assign _028_[20] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[20] : 1'hx;
  assign _028_[21] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[21] : 1'hx;
  assign _028_[22] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[22] : 1'hx;
  assign _028_[23] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[23] : 1'hx;
  assign _028_[24] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[24] : 1'hx;
  assign _028_[25] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[25] : 1'hx;
  assign _028_[26] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[26] : 1'hx;
  assign _028_[27] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[27] : 1'hx;
  assign _028_[28] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[28] : 1'hx;
  assign _028_[29] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[29] : 1'hx;
  assign _028_[30] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[30] : 1'hx;
  assign _028_[31] = _003_ ? (* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _029_[31] : 1'hx;
  assign _038_ = ~(* src = "ahb_master.v:113.25-113.41" *) _037_[2];
  assign _034_[0] = ~(* src = "ahb_master.v:113.25-113.41|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) burst_cnt[0];
  assign _036_[1] = ~(* src = "ahb_master.v:113.25-113.41|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) burst_cnt[1];
  assign _036_[2] = ~(* src = "ahb_master.v:113.25-113.41|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) burst_cnt[2];
  assign _031_[2] = ~(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *) HADDR[2];
  assign _037_[1] = _036_[1] &(* src = "ahb_master.v:113.25-113.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _034_[0];
  assign _039_ = burst_cnt[2] &(* src = "ahb_master.v:113.25-113.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _037_[1];
  assign _037_[2] = _036_[2] |(* src = "ahb_master.v:113.25-113.41|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.12-248.41" *)  _039_;
  assign _030_[3] = HADDR[3] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  HADDR[2];
  assign _030_[7] = _055_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _030_[3];
  assign _030_[15] = _061_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  _030_[7];
  assign _042_ = HADDR[5] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[4];
  assign _043_ = HADDR[7] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[6];
  assign _044_ = HADDR[9] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[8];
  assign _045_ = HADDR[11] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[10];
  assign _046_ = HADDR[13] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[12];
  assign _047_ = HADDR[15] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[14];
  assign _048_ = HADDR[17] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[16];
  assign _049_ = HADDR[19] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[18];
  assign _050_ = HADDR[21] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[20];
  assign _051_ = HADDR[23] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[22];
  assign _052_ = HADDR[25] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[24];
  assign _053_ = HADDR[27] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[26];
  assign _054_ = HADDR[29] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  HADDR[28];
  assign _055_ = _043_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _042_;
  assign _056_ = _045_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _044_;
  assign _057_ = _047_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _046_;
  assign _058_ = _049_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _048_;
  assign _059_ = _051_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _050_;
  assign _060_ = _053_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _052_;
  assign _061_ = _057_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _056_;
  assign _062_ = _059_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)  _058_;
  assign _030_[23] = _062_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[15];
  assign _030_[11] = _056_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[7];
  assign _030_[19] = _058_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[15];
  assign _030_[27] = _060_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[23];
  assign _030_[5] = _042_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[3];
  assign _030_[9] = _044_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[7];
  assign _030_[13] = _046_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[11];
  assign _030_[17] = _048_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[15];
  assign _030_[21] = _050_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[19];
  assign _030_[25] = _052_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[23];
  assign _030_[29] = _054_ &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[27];
  assign _030_[4] = HADDR[4] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[3];
  assign _030_[6] = HADDR[6] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[5];
  assign _030_[8] = HADDR[8] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[7];
  assign _030_[10] = HADDR[10] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[9];
  assign _030_[12] = HADDR[12] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[11];
  assign _030_[14] = HADDR[14] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[13];
  assign _030_[16] = HADDR[16] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[15];
  assign _030_[18] = HADDR[18] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[17];
  assign _030_[20] = HADDR[20] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[19];
  assign _030_[22] = HADDR[22] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[21];
  assign _030_[24] = HADDR[24] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[23];
  assign _030_[26] = HADDR[26] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[25];
  assign _030_[28] = HADDR[28] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[27];
  assign _030_[30] = HADDR[30] &(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)  _030_[29];
  assign _033_[1] = burst_cnt[1] &(* src = "ahb_master.v:117.39-117.55|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)  burst_cnt[0];
  assign _040_ = _038_ | _039_;
  assign _018_[0] = _017_[0] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _018_[1] = _017_[1] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _018_[2] = _017_[2] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _022_[4] = _021_[4] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _022_[5] = _021_[5] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _022_[1] = _021_[1] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[32] = _026_[32] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[33] = _026_[33] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[34] = _026_[34] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[35] = _026_[35] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[36] = _026_[36] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[37] = _026_[37] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[38] = _026_[38] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[39] = _026_[39] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[40] = _026_[40] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[41] = _026_[41] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[42] = _026_[42] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[43] = _026_[43] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[44] = _026_[44] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[45] = _026_[45] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[46] = _026_[46] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[47] = _026_[47] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[48] = _026_[48] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[49] = _026_[49] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[50] = _026_[50] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[51] = _026_[51] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[52] = _026_[52] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[53] = _026_[53] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[54] = _026_[54] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[55] = _026_[55] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[56] = _026_[56] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[57] = _026_[57] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[58] = _026_[58] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[59] = _026_[59] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[60] = _026_[60] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[61] = _026_[61] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[62] = _026_[62] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[63] = _026_[63] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _023_[2];
  assign _027_[0] = _026_[0] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[1] = _026_[1] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[2] = _026_[2] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[3] = _026_[3] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[4] = _026_[4] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[5] = _026_[5] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[6] = _026_[6] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[7] = _026_[7] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[8] = _026_[8] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[9] = _026_[9] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[10] = _026_[10] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[11] = _026_[11] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[12] = _026_[12] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[13] = _026_[13] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[14] = _026_[14] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[15] = _026_[15] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[16] = _026_[16] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[17] = _026_[17] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[18] = _026_[18] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[19] = _026_[19] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[20] = _026_[20] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[21] = _026_[21] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[22] = _026_[22] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[23] = _026_[23] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[24] = _026_[24] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[25] = _026_[25] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[26] = _026_[26] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[27] = _026_[27] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[28] = _026_[28] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[29] = _026_[29] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[30] = _026_[30] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _027_[31] = _026_[31] &(* src = "ahb_master.v:0.0-0.0|ahb_master.v:86.13-136.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _019_[0];
  assign _032_[3] = HADDR[3] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  HADDR[2];
  assign _032_[4] = HADDR[4] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[3];
  assign _032_[5] = HADDR[5] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[4];
  assign _032_[6] = HADDR[6] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[5];
  assign _032_[7] = HADDR[7] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[6];
  assign _032_[8] = HADDR[8] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[7];
  assign _032_[9] = HADDR[9] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[8];
  assign _032_[10] = HADDR[10] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[9];
  assign _032_[11] = HADDR[11] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[10];
  assign _032_[12] = HADDR[12] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[11];
  assign _032_[13] = HADDR[13] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[12];
  assign _032_[14] = HADDR[14] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[13];
  assign _032_[15] = HADDR[15] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[14];
  assign _032_[16] = HADDR[16] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[15];
  assign _032_[17] = HADDR[17] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[16];
  assign _032_[18] = HADDR[18] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[17];
  assign _032_[19] = HADDR[19] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[18];
  assign _032_[20] = HADDR[20] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[19];
  assign _032_[21] = HADDR[21] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[20];
  assign _032_[22] = HADDR[22] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[21];
  assign _032_[23] = HADDR[23] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[22];
  assign _032_[24] = HADDR[24] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[23];
  assign _032_[25] = HADDR[25] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[24];
  assign _032_[26] = HADDR[26] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[25];
  assign _032_[27] = HADDR[27] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[26];
  assign _032_[28] = HADDR[28] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[27];
  assign _032_[29] = HADDR[29] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[28];
  assign _032_[30] = HADDR[30] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[29];
  assign _032_[31] = HADDR[31] ^(* src = "ahb_master.v:115.39-115.52|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _030_[30];
  assign _035_[1] = burst_cnt[1] ^(* src = "ahb_master.v:117.39-117.55|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  burst_cnt[0];
  assign _035_[2] = burst_cnt[2] ^(* src = "ahb_master.v:117.39-117.55|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)  _033_[1];
  assign _014_[0] = _006_;
  assign _017_[5:3] = 3'h0;
  assign _018_[5:3] = 3'h0;
  assign { _021_[3:2], _021_[0] } = { 2'h3, _021_[1] };
  assign { _022_[3:2], _022_[0] } = { _019_[1], _019_[1], _022_[1] };
  assign _023_[1:0] = _019_;
  assign _030_[2:0] = { HADDR[2], 2'h0 };
  assign { _031_[31:3], _031_[1:0] } = { HADDR[31:3], HADDR[1:0] };
  assign _032_[2:0] = { _031_[2], HADDR[1:0] };
  assign _033_[0] = burst_cnt[0];
  assign _034_[2:1] = burst_cnt[2:1];
  assign _035_[0] = _034_[0];
  assign _036_[0] = _034_[0];
  assign _037_[0] = _034_[0];
  assign HBURST[2:1] = { 1'h0, HBURST[0] };
  assign HPROT = 4'h3;
  assign HSIZE = { 1'h0, HBURST[0], 1'h0 };
  assign HWDATA = 32'd0;
endmodule
