/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "abp_peripheral.v:1.1-113.10" *)
module apb_timer_peripheral(clk, rst_n, paddr, psel, penable, pwrite, pwdata, prdata, pready, pslverr, done_out);
  (* src = "abp_peripheral.v:43.1-79.4" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  (* force_downto = 32'd1 *)
  (* src = "abp_peripheral.v:0.0-0.0|abp_peripheral.v:69.17-74.24|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [31:0] _224_;
  (* src = "abp_peripheral.v:6.34-6.37" *)
  input clk;
  wire clk;
  (* src = "abp_peripheral.v:36.22-36.30" *)
  reg ctrl_reg;
  (* src = "abp_peripheral.v:22.34-22.42" *)
  output done_out;
  wire done_out;
  (* src = "abp_peripheral.v:35.22-35.30" *)
  reg [31:0] load_reg;
  (* src = "abp_peripheral.v:10.34-10.39" *)
  input [31:0] paddr;
  wire [31:0] paddr;
  (* src = "abp_peripheral.v:12.34-12.41" *)
  input penable;
  wire penable;
  (* src = "abp_peripheral.v:17.34-17.40" *)
  output [31:0] prdata;
  reg [31:0] prdata;
  (* src = "abp_peripheral.v:18.34-18.40" *)
  output pready;
  reg pready;
  (* src = "abp_peripheral.v:11.34-11.38" *)
  input psel;
  wire psel;
  (* src = "abp_peripheral.v:19.34-19.41" *)
  output pslverr;
  reg pslverr;
  (* src = "abp_peripheral.v:14.34-14.40" *)
  input [31:0] pwdata;
  wire [31:0] pwdata;
  (* src = "abp_peripheral.v:13.34-13.40" *)
  input pwrite;
  wire pwrite;
  (* src = "abp_peripheral.v:7.34-7.39" *)
  input rst_n;
  wire rst_n;
  (* src = "abp_peripheral.v:37.22-37.30" *)
  reg stat_reg;
  (* src = "abp_peripheral.v:38.22-38.33" *)
  reg [31:0] timer_count;
  assign _005_ = ~(penable & psel);
  assign _006_ = pwrite & ~(_005_);
  assign _007_ = paddr[1] | paddr[0];
  assign _008_ = paddr[3] | ~(paddr[2]);
  assign _009_ = _008_ | _007_;
  assign _010_ = paddr[5] | paddr[4];
  assign _011_ = paddr[7] | paddr[6];
  assign _012_ = _011_ | _010_;
  assign _013_ = _012_ | _009_;
  assign _014_ = paddr[9] | paddr[8];
  assign _015_ = paddr[11] | paddr[10];
  assign _016_ = _015_ | _014_;
  assign _017_ = paddr[13] | paddr[12];
  assign _018_ = paddr[15] | paddr[14];
  assign _019_ = _018_ | _017_;
  assign _020_ = _019_ | _016_;
  assign _021_ = _020_ | _013_;
  assign _022_ = paddr[17] | paddr[16];
  assign _023_ = paddr[19] | paddr[18];
  assign _024_ = _023_ | _022_;
  assign _025_ = paddr[21] | paddr[20];
  assign _026_ = paddr[23] | paddr[22];
  assign _027_ = _026_ | _025_;
  assign _028_ = _027_ | _024_;
  assign _029_ = paddr[25] | paddr[24];
  assign _030_ = paddr[27] | paddr[26];
  assign _031_ = _030_ | _029_;
  assign _032_ = paddr[29] | paddr[28];
  assign _033_ = paddr[31] | paddr[30];
  assign _034_ = _033_ | _032_;
  assign _035_ = _034_ | _031_;
  assign _036_ = _035_ | _028_;
  assign _037_ = _036_ | _021_;
  assign _002_ = _006_ & ~(_037_);
  assign _038_ = timer_count[0] & ~(timer_count[1]);
  assign _039_ = ~(timer_count[3] | timer_count[2]);
  assign _040_ = _039_ & _038_;
  assign _041_ = ~(timer_count[5] | timer_count[4]);
  assign _042_ = ~(timer_count[7] | timer_count[6]);
  assign _043_ = _042_ & _041_;
  assign _044_ = _043_ & _040_;
  assign _045_ = ~(timer_count[9] | timer_count[8]);
  assign _046_ = ~(timer_count[11] | timer_count[10]);
  assign _047_ = _046_ & _045_;
  assign _048_ = timer_count[13] | timer_count[12];
  assign _049_ = ~(timer_count[15] | timer_count[14]);
  assign _050_ = _048_ | ~(_049_);
  assign _051_ = _047_ & ~(_050_);
  assign _052_ = ~(_051_ & _044_);
  assign _053_ = ~(timer_count[17] | timer_count[16]);
  assign _054_ = ~(timer_count[19] | timer_count[18]);
  assign _055_ = _054_ & _053_;
  assign _056_ = timer_count[21] | timer_count[20];
  assign _057_ = ~(timer_count[23] | timer_count[22]);
  assign _058_ = _056_ | ~(_057_);
  assign _059_ = _055_ & ~(_058_);
  assign _060_ = ~(timer_count[25] | timer_count[24]);
  assign _061_ = ~(timer_count[27] | timer_count[26]);
  assign _062_ = _061_ & _060_;
  assign _063_ = ~(timer_count[29] | timer_count[28]);
  assign _064_ = ~(timer_count[31] | timer_count[30]);
  assign _065_ = _064_ & _063_;
  assign _066_ = ~(_065_ & _062_);
  assign _067_ = _066_ | ~(_059_);
  assign _068_ = _067_ | _052_;
  assign _069_ = ctrl_reg & ~(_068_);
  assign _070_ = ~(timer_count[1] | timer_count[0]);
  assign _071_ = _070_ & _039_;
  assign _072_ = _071_ & _043_;
  assign _073_ = ~(_072_ & _051_);
  assign _074_ = ~(_073_ | _067_);
  assign _001_ = _069_ & ~(_074_);
  assign _075_ = paddr[2] | paddr[3];
  assign _076_ = _075_ | _007_;
  assign _077_ = _076_ | _012_;
  assign _078_ = _077_ | _020_;
  assign _079_ = ~(_078_ | _036_);
  assign _003_ = _079_ & _006_;
  assign _080_ = ~pwrite;
  assign _081_ = _080_ & ~(_005_);
  assign _082_ = paddr[2] | ~(paddr[3]);
  assign _083_ = _082_ | _007_;
  assign _084_ = _083_ | _012_;
  assign _085_ = _084_ | _020_;
  assign _086_ = ~(_085_ | _036_);
  assign _087_ = _086_ | ~(_037_);
  assign _088_ = ~(_087_ | _079_);
  assign _004_ = _081_ & ~(_088_);
  assign _089_ = _086_ & stat_reg;
  assign _090_ = ctrl_reg & ~(_037_);
  assign _091_ = _090_ | _089_;
  assign _224_[0] = _087_ ? _091_ : load_reg[0];
  assign _224_[1] = load_reg[1] & ~(_087_);
  assign _224_[2] = load_reg[2] & ~(_087_);
  assign _224_[3] = load_reg[3] & ~(_087_);
  assign _224_[4] = load_reg[4] & ~(_087_);
  assign _224_[5] = load_reg[5] & ~(_087_);
  assign _224_[6] = load_reg[6] & ~(_087_);
  assign _224_[7] = load_reg[7] & ~(_087_);
  assign _224_[8] = load_reg[8] & ~(_087_);
  assign _224_[9] = load_reg[9] & ~(_087_);
  assign _224_[10] = load_reg[10] & ~(_087_);
  assign _224_[11] = load_reg[11] & ~(_087_);
  assign _224_[12] = load_reg[12] & ~(_087_);
  assign _224_[13] = load_reg[13] & ~(_087_);
  assign _224_[14] = load_reg[14] & ~(_087_);
  assign _224_[15] = load_reg[15] & ~(_087_);
  assign _224_[16] = load_reg[16] & ~(_087_);
  assign _224_[17] = load_reg[17] & ~(_087_);
  assign _224_[18] = load_reg[18] & ~(_087_);
  assign _224_[19] = load_reg[19] & ~(_087_);
  assign _224_[20] = load_reg[20] & ~(_087_);
  assign _224_[21] = load_reg[21] & ~(_087_);
  assign _224_[22] = load_reg[22] & ~(_087_);
  assign _224_[23] = load_reg[23] & ~(_087_);
  assign _224_[24] = load_reg[24] & ~(_087_);
  assign _224_[25] = load_reg[25] & ~(_087_);
  assign _224_[26] = load_reg[26] & ~(_087_);
  assign _224_[27] = load_reg[27] & ~(_087_);
  assign _224_[28] = load_reg[28] & ~(_087_);
  assign _224_[29] = load_reg[29] & ~(_087_);
  assign _224_[30] = load_reg[30] & ~(_087_);
  assign _224_[31] = load_reg[31] & ~(_087_);
  assign _092_ = ~timer_count[0];
  assign _192_ = _074_ ? load_reg[0] : _092_;
  assign _093_ = ~(timer_count[1] ^ timer_count[0]);
  assign _203_ = _074_ ? load_reg[1] : _093_;
  assign _094_ = _070_ ^ timer_count[2];
  assign _214_ = _074_ ? load_reg[2] : _094_;
  assign _095_ = _070_ & ~(timer_count[2]);
  assign _096_ = _095_ ^ timer_count[3];
  assign _217_ = _074_ ? load_reg[3] : _096_;
  assign _097_ = _039_ & ~(_070_);
  assign _098_ = _039_ & ~(_097_);
  assign _099_ = _098_ ^ timer_count[4];
  assign _218_ = _074_ ? load_reg[4] : _099_;
  assign _100_ = _098_ & ~(timer_count[4]);
  assign _101_ = _100_ ^ timer_count[5];
  assign _219_ = _074_ ? load_reg[5] : _101_;
  assign _102_ = _041_ & ~(_098_);
  assign _103_ = _041_ & ~(_102_);
  assign _104_ = _103_ ^ timer_count[6];
  assign _220_ = _074_ ? load_reg[6] : _104_;
  assign _105_ = _103_ & ~(timer_count[6]);
  assign _106_ = _105_ ^ timer_count[7];
  assign _221_ = _074_ ? load_reg[7] : _106_;
  assign _107_ = _042_ & ~(_041_);
  assign _108_ = _042_ & ~(_107_);
  assign _109_ = _043_ & ~(_098_);
  assign _110_ = _108_ & ~(_109_);
  assign _111_ = _110_ ^ timer_count[8];
  assign _222_ = _074_ ? load_reg[8] : _111_;
  assign _112_ = _110_ & ~(timer_count[8]);
  assign _113_ = _112_ ^ timer_count[9];
  assign _223_ = _074_ ? load_reg[9] : _113_;
  assign _114_ = _045_ & ~(_110_);
  assign _115_ = _045_ & ~(_114_);
  assign _116_ = _115_ ^ timer_count[10];
  assign _193_ = _074_ ? load_reg[10] : _116_;
  assign _117_ = _115_ & ~(timer_count[10]);
  assign _118_ = _117_ ^ timer_count[11];
  assign _194_ = _074_ ? load_reg[11] : _118_;
  assign _119_ = _046_ & ~(_045_);
  assign _120_ = _046_ & ~(_119_);
  assign _121_ = _047_ & ~(_110_);
  assign _122_ = _120_ & ~(_121_);
  assign _123_ = _122_ ^ timer_count[12];
  assign _195_ = _074_ ? load_reg[12] : _123_;
  assign _124_ = _122_ & ~(timer_count[12]);
  assign _125_ = _124_ ^ timer_count[13];
  assign _196_ = _074_ ? load_reg[13] : _125_;
  assign _126_ = ~timer_count[14];
  assign _127_ = ~(timer_count[13] | timer_count[12]);
  assign _128_ = ~(_122_ | _048_);
  assign _129_ = _128_ | ~(_127_);
  assign _130_ = _129_ ^ _126_;
  assign _197_ = _074_ ? load_reg[14] : _130_;
  assign _131_ = _126_ & ~(_129_);
  assign _132_ = _131_ ^ timer_count[15];
  assign _198_ = _074_ ? load_reg[15] : _132_;
  assign _133_ = _049_ & ~(_127_);
  assign _134_ = _049_ & ~(_133_);
  assign _135_ = ~(_120_ | _050_);
  assign _136_ = _134_ & ~(_135_);
  assign _137_ = _051_ & ~(_110_);
  assign _138_ = _136_ & ~(_137_);
  assign _139_ = _138_ ^ timer_count[16];
  assign _199_ = _074_ ? load_reg[16] : _139_;
  assign _140_ = _138_ & ~(timer_count[16]);
  assign _141_ = _140_ ^ timer_count[17];
  assign _200_ = _074_ ? load_reg[17] : _141_;
  assign _142_ = ~timer_count[18];
  assign _143_ = _053_ & ~(_138_);
  assign _144_ = _143_ | ~(_053_);
  assign _145_ = _144_ ^ _142_;
  assign _201_ = _074_ ? load_reg[18] : _145_;
  assign _146_ = _142_ & ~(_144_);
  assign _147_ = _146_ ^ timer_count[19];
  assign _202_ = _074_ ? load_reg[19] : _147_;
  assign _148_ = _054_ & ~(_053_);
  assign _149_ = _054_ & ~(_148_);
  assign _150_ = _055_ & ~(_138_);
  assign _151_ = _149_ & ~(_150_);
  assign _152_ = _151_ ^ timer_count[20];
  assign _204_ = _074_ ? load_reg[20] : _152_;
  assign _153_ = _151_ & ~(timer_count[20]);
  assign _154_ = _153_ ^ timer_count[21];
  assign _205_ = _074_ ? load_reg[21] : _154_;
  assign _155_ = ~timer_count[22];
  assign _156_ = ~(timer_count[21] | timer_count[20]);
  assign _157_ = ~(_151_ | _056_);
  assign _158_ = _157_ | ~(_156_);
  assign _159_ = _158_ ^ _155_;
  assign _206_ = _074_ ? load_reg[22] : _159_;
  assign _160_ = _155_ & ~(_158_);
  assign _161_ = _160_ ^ timer_count[23];
  assign _207_ = _074_ ? load_reg[23] : _161_;
  assign _162_ = _057_ & ~(_156_);
  assign _163_ = _057_ & ~(_162_);
  assign _164_ = ~(_149_ | _058_);
  assign _165_ = _163_ & ~(_164_);
  assign _166_ = _059_ & ~(_138_);
  assign _167_ = _165_ & ~(_166_);
  assign _168_ = _167_ ^ timer_count[24];
  assign _208_ = _074_ ? load_reg[24] : _168_;
  assign _169_ = _167_ & ~(timer_count[24]);
  assign _170_ = _169_ ^ timer_count[25];
  assign _209_ = _074_ ? load_reg[25] : _170_;
  assign _171_ = ~timer_count[26];
  assign _172_ = _060_ & ~(_167_);
  assign _173_ = _172_ | ~(_060_);
  assign _174_ = _173_ ^ _171_;
  assign _210_ = _074_ ? load_reg[26] : _174_;
  assign _175_ = _171_ & ~(_173_);
  assign _176_ = _175_ ^ timer_count[27];
  assign _211_ = _074_ ? load_reg[27] : _176_;
  assign _177_ = _061_ & ~(_060_);
  assign _178_ = _061_ & ~(_177_);
  assign _179_ = _062_ & ~(_167_);
  assign _180_ = _178_ & ~(_179_);
  assign _181_ = _180_ ^ timer_count[28];
  assign _212_ = _074_ ? load_reg[28] : _181_;
  assign _182_ = _180_ & ~(timer_count[28]);
  assign _183_ = _182_ ^ timer_count[29];
  assign _213_ = _074_ ? load_reg[29] : _183_;
  assign _184_ = ~timer_count[30];
  assign _185_ = _063_ & ~(_180_);
  assign _186_ = _185_ | ~(_063_);
  assign _187_ = _186_ ^ _184_;
  assign _215_ = _074_ ? load_reg[30] : _187_;
  assign _188_ = _184_ & ~(_186_);
  assign _189_ = _188_ ^ timer_count[31];
  assign _216_ = _074_ ? load_reg[31] : _189_;
  assign _190_ = _037_ & ~(_079_);
  assign _191_ = pwrite ? _190_ : _088_;
  assign _000_ = _191_ & ~(_005_);
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg <= 1'h0;
    else if (_002_) ctrl_reg <= pwdata[0];
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) stat_reg <= 1'h0;
    else if (_001_) stat_reg <= 1'h1;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[0] <= 1'h0;
    else if (ctrl_reg) timer_count[0] <= _192_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[1] <= 1'h0;
    else if (ctrl_reg) timer_count[1] <= _203_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[2] <= 1'h0;
    else if (ctrl_reg) timer_count[2] <= _214_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[3] <= 1'h0;
    else if (ctrl_reg) timer_count[3] <= _217_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[4] <= 1'h0;
    else if (ctrl_reg) timer_count[4] <= _218_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[5] <= 1'h0;
    else if (ctrl_reg) timer_count[5] <= _219_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[6] <= 1'h0;
    else if (ctrl_reg) timer_count[6] <= _220_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[7] <= 1'h0;
    else if (ctrl_reg) timer_count[7] <= _221_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[8] <= 1'h0;
    else if (ctrl_reg) timer_count[8] <= _222_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[9] <= 1'h0;
    else if (ctrl_reg) timer_count[9] <= _223_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[10] <= 1'h0;
    else if (ctrl_reg) timer_count[10] <= _193_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[11] <= 1'h0;
    else if (ctrl_reg) timer_count[11] <= _194_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[12] <= 1'h0;
    else if (ctrl_reg) timer_count[12] <= _195_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[13] <= 1'h0;
    else if (ctrl_reg) timer_count[13] <= _196_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[14] <= 1'h0;
    else if (ctrl_reg) timer_count[14] <= _197_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[15] <= 1'h0;
    else if (ctrl_reg) timer_count[15] <= _198_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[16] <= 1'h0;
    else if (ctrl_reg) timer_count[16] <= _199_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[17] <= 1'h0;
    else if (ctrl_reg) timer_count[17] <= _200_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[18] <= 1'h0;
    else if (ctrl_reg) timer_count[18] <= _201_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[19] <= 1'h0;
    else if (ctrl_reg) timer_count[19] <= _202_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[20] <= 1'h0;
    else if (ctrl_reg) timer_count[20] <= _204_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[21] <= 1'h0;
    else if (ctrl_reg) timer_count[21] <= _205_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[22] <= 1'h0;
    else if (ctrl_reg) timer_count[22] <= _206_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[23] <= 1'h0;
    else if (ctrl_reg) timer_count[23] <= _207_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[24] <= 1'h0;
    else if (ctrl_reg) timer_count[24] <= _208_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[25] <= 1'h0;
    else if (ctrl_reg) timer_count[25] <= _209_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[26] <= 1'h0;
    else if (ctrl_reg) timer_count[26] <= _210_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[27] <= 1'h0;
    else if (ctrl_reg) timer_count[27] <= _211_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[28] <= 1'h0;
    else if (ctrl_reg) timer_count[28] <= _212_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[29] <= 1'h0;
    else if (ctrl_reg) timer_count[29] <= _213_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[30] <= 1'h0;
    else if (ctrl_reg) timer_count[30] <= _215_;
  (* src = "abp_peripheral.v:84.1-111.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timer_count[31] <= 1'h0;
    else if (ctrl_reg) timer_count[31] <= _216_;
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pready <= 1'h0;
    else pready <= 1'h1;
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pslverr <= 1'h0;
    else pslverr <= _000_;
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[0] <= 1'h0;
    else if (_004_) prdata[0] <= _224_[0];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[1] <= 1'h0;
    else if (_004_) prdata[1] <= _224_[1];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[2] <= 1'h0;
    else if (_004_) prdata[2] <= _224_[2];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[3] <= 1'h0;
    else if (_004_) prdata[3] <= _224_[3];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[4] <= 1'h0;
    else if (_004_) prdata[4] <= _224_[4];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[5] <= 1'h0;
    else if (_004_) prdata[5] <= _224_[5];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[6] <= 1'h0;
    else if (_004_) prdata[6] <= _224_[6];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[7] <= 1'h0;
    else if (_004_) prdata[7] <= _224_[7];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[8] <= 1'h0;
    else if (_004_) prdata[8] <= _224_[8];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[9] <= 1'h0;
    else if (_004_) prdata[9] <= _224_[9];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[10] <= 1'h0;
    else if (_004_) prdata[10] <= _224_[10];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[11] <= 1'h0;
    else if (_004_) prdata[11] <= _224_[11];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[12] <= 1'h0;
    else if (_004_) prdata[12] <= _224_[12];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[13] <= 1'h0;
    else if (_004_) prdata[13] <= _224_[13];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[14] <= 1'h0;
    else if (_004_) prdata[14] <= _224_[14];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[15] <= 1'h0;
    else if (_004_) prdata[15] <= _224_[15];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[16] <= 1'h0;
    else if (_004_) prdata[16] <= _224_[16];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[17] <= 1'h0;
    else if (_004_) prdata[17] <= _224_[17];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[18] <= 1'h0;
    else if (_004_) prdata[18] <= _224_[18];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[19] <= 1'h0;
    else if (_004_) prdata[19] <= _224_[19];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[20] <= 1'h0;
    else if (_004_) prdata[20] <= _224_[20];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[21] <= 1'h0;
    else if (_004_) prdata[21] <= _224_[21];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[22] <= 1'h0;
    else if (_004_) prdata[22] <= _224_[22];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[23] <= 1'h0;
    else if (_004_) prdata[23] <= _224_[23];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[24] <= 1'h0;
    else if (_004_) prdata[24] <= _224_[24];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[25] <= 1'h0;
    else if (_004_) prdata[25] <= _224_[25];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[26] <= 1'h0;
    else if (_004_) prdata[26] <= _224_[26];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[27] <= 1'h0;
    else if (_004_) prdata[27] <= _224_[27];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[28] <= 1'h0;
    else if (_004_) prdata[28] <= _224_[28];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[29] <= 1'h0;
    else if (_004_) prdata[29] <= _224_[29];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[30] <= 1'h0;
    else if (_004_) prdata[30] <= _224_[30];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata[31] <= 1'h0;
    else if (_004_) prdata[31] <= _224_[31];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[0] <= 1'h0;
    else if (_003_) load_reg[0] <= pwdata[0];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[1] <= 1'h0;
    else if (_003_) load_reg[1] <= pwdata[1];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[2] <= 1'h0;
    else if (_003_) load_reg[2] <= pwdata[2];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[3] <= 1'h0;
    else if (_003_) load_reg[3] <= pwdata[3];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[4] <= 1'h0;
    else if (_003_) load_reg[4] <= pwdata[4];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[5] <= 1'h0;
    else if (_003_) load_reg[5] <= pwdata[5];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[6] <= 1'h0;
    else if (_003_) load_reg[6] <= pwdata[6];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[7] <= 1'h0;
    else if (_003_) load_reg[7] <= pwdata[7];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[8] <= 1'h0;
    else if (_003_) load_reg[8] <= pwdata[8];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[9] <= 1'h0;
    else if (_003_) load_reg[9] <= pwdata[9];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[10] <= 1'h0;
    else if (_003_) load_reg[10] <= pwdata[10];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[11] <= 1'h0;
    else if (_003_) load_reg[11] <= pwdata[11];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[12] <= 1'h0;
    else if (_003_) load_reg[12] <= pwdata[12];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[13] <= 1'h0;
    else if (_003_) load_reg[13] <= pwdata[13];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[14] <= 1'h0;
    else if (_003_) load_reg[14] <= pwdata[14];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[15] <= 1'h0;
    else if (_003_) load_reg[15] <= pwdata[15];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[16] <= 1'h0;
    else if (_003_) load_reg[16] <= pwdata[16];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[17] <= 1'h0;
    else if (_003_) load_reg[17] <= pwdata[17];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[18] <= 1'h0;
    else if (_003_) load_reg[18] <= pwdata[18];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[19] <= 1'h0;
    else if (_003_) load_reg[19] <= pwdata[19];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[20] <= 1'h0;
    else if (_003_) load_reg[20] <= pwdata[20];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[21] <= 1'h0;
    else if (_003_) load_reg[21] <= pwdata[21];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[22] <= 1'h0;
    else if (_003_) load_reg[22] <= pwdata[22];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[23] <= 1'h0;
    else if (_003_) load_reg[23] <= pwdata[23];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[24] <= 1'h0;
    else if (_003_) load_reg[24] <= pwdata[24];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[25] <= 1'h0;
    else if (_003_) load_reg[25] <= pwdata[25];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[26] <= 1'h0;
    else if (_003_) load_reg[26] <= pwdata[26];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[27] <= 1'h0;
    else if (_003_) load_reg[27] <= pwdata[27];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[28] <= 1'h0;
    else if (_003_) load_reg[28] <= pwdata[28];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[29] <= 1'h0;
    else if (_003_) load_reg[29] <= pwdata[29];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[30] <= 1'h0;
    else if (_003_) load_reg[30] <= pwdata[30];
  (* src = "abp_peripheral.v:43.1-79.4" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) load_reg[31] <= 1'h0;
    else if (_003_) load_reg[31] <= pwdata[31];
  assign done_out = stat_reg;
endmodule
