/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "axi4_master_write.v:1.1-123.10" *)
module axi4_master_write(clk, rst_n, write_req, addr_in, data_in, strb_in, write_done, awaddr, awvalid, awready, wdata, wstrb, wvalid, wready, bresp, bvalid, bready);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire [1:0] _027_;
  wire [1:0] _028_;
  wire _029_;
  wire _030_;
  wire [1:0] _031_;
  wire [1:0] _032_;
  wire [1:0] _033_;
  wire [1:0] _034_;
  wire [1:0] _035_;
  wire _036_;
  (* src = "axi4_master_write.v:97.26-97.42" *)
  wire _037_;
  (* src = "axi4_master_write.v:97.48-97.62" *)
  wire _038_;
  wire _039_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [1:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _041_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [1:0] _042_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _043_;
  wire _044_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [1:0] _045_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _046_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _047_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [7:0] _048_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [7:0] _049_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [3:0] _050_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [1:0] _051_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [1:0] _052_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [1:0] _053_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _054_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _055_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _056_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [1:0] _057_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _058_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _059_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _060_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [1:0] _061_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _062_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _063_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _064_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [1:0] _065_;
  (* force_downto = 32'd1 *)
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _066_;
  (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _067_;
  (* src = "axi4_master_write.v:11.37-11.44" *)
  input [3:0] addr_in;
  wire [3:0] addr_in;
  (* src = "axi4_master_write.v:41.9-41.16" *)
  reg aw_done;
  (* src = "axi4_master_write.v:45.10-45.15" *)
  wire aw_hs;
  (* src = "axi4_master_write.v:17.37-17.43" *)
  output [3:0] awaddr;
  reg [3:0] awaddr;
  (* src = "axi4_master_write.v:19.37-19.44" *)
  input awready;
  wire awready;
  (* src = "axi4_master_write.v:18.37-18.44" *)
  output awvalid;
  reg awvalid;
  (* src = "axi4_master_write.v:30.37-30.43" *)
  output bready;
  reg bready;
  (* src = "axi4_master_write.v:28.37-28.42" *)
  input [1:0] bresp;
  wire [1:0] bresp;
  (* src = "axi4_master_write.v:29.37-29.43" *)
  input bvalid;
  wire bvalid;
  (* src = "axi4_master_write.v:6.37-6.40" *)
  input clk;
  wire clk;
  (* src = "axi4_master_write.v:12.37-12.44" *)
  input [31:0] data_in;
  wire [31:0] data_in;
  (* src = "axi4_master_write.v:7.37-7.42" *)
  input rst_n;
  wire rst_n;
  (* src = "axi4_master_write.v:34.15-34.20" *)
  reg [1:0] state;
  (* src = "axi4_master_write.v:13.37-13.44" *)
  input [3:0] strb_in;
  wire [3:0] strb_in;
  (* src = "axi4_master_write.v:42.9-42.15" *)
  reg w_done;
  (* src = "axi4_master_write.v:46.10-46.14" *)
  wire w_hs;
  (* src = "axi4_master_write.v:22.37-22.42" *)
  output [31:0] wdata;
  reg [31:0] wdata;
  (* src = "axi4_master_write.v:25.37-25.43" *)
  input wready;
  wire wready;
  (* src = "axi4_master_write.v:14.37-14.47" *)
  output write_done;
  reg write_done;
  (* src = "axi4_master_write.v:10.37-10.46" *)
  input write_req;
  wire write_req;
  (* src = "axi4_master_write.v:23.37-23.42" *)
  output [3:0] wstrb;
  reg [3:0] wstrb;
  (* src = "axi4_master_write.v:24.37-24.43" *)
  output wvalid;
  reg wvalid;
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) write_done <= 1'h0;
    else if (_011_) write_done <= _066_;
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) awaddr[0] <= 1'h0;
    else if (_012_) awaddr[0] <= addr_in[0];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) awaddr[1] <= 1'h0;
    else if (_012_) awaddr[1] <= addr_in[1];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) awaddr[2] <= 1'h0;
    else if (_012_) awaddr[2] <= addr_in[2];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) awaddr[3] <= 1'h0;
    else if (_012_) awaddr[3] <= addr_in[3];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) awvalid <= 1'h0;
    else if (_013_) awvalid <= _063_;
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[0] <= 1'h0;
    else if (_012_) wdata[0] <= data_in[0];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[1] <= 1'h0;
    else if (_012_) wdata[1] <= data_in[1];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[2] <= 1'h0;
    else if (_012_) wdata[2] <= data_in[2];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[3] <= 1'h0;
    else if (_012_) wdata[3] <= data_in[3];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[4] <= 1'h0;
    else if (_012_) wdata[4] <= data_in[4];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[5] <= 1'h0;
    else if (_012_) wdata[5] <= data_in[5];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[6] <= 1'h0;
    else if (_012_) wdata[6] <= data_in[6];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[7] <= 1'h0;
    else if (_012_) wdata[7] <= data_in[7];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[8] <= 1'h0;
    else if (_012_) wdata[8] <= data_in[8];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[9] <= 1'h0;
    else if (_012_) wdata[9] <= data_in[9];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[10] <= 1'h0;
    else if (_012_) wdata[10] <= data_in[10];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[11] <= 1'h0;
    else if (_012_) wdata[11] <= data_in[11];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[12] <= 1'h0;
    else if (_012_) wdata[12] <= data_in[12];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[13] <= 1'h0;
    else if (_012_) wdata[13] <= data_in[13];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[14] <= 1'h0;
    else if (_012_) wdata[14] <= data_in[14];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[15] <= 1'h0;
    else if (_012_) wdata[15] <= data_in[15];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[16] <= 1'h0;
    else if (_012_) wdata[16] <= data_in[16];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[17] <= 1'h0;
    else if (_012_) wdata[17] <= data_in[17];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[18] <= 1'h0;
    else if (_012_) wdata[18] <= data_in[18];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[19] <= 1'h0;
    else if (_012_) wdata[19] <= data_in[19];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[20] <= 1'h0;
    else if (_012_) wdata[20] <= data_in[20];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[21] <= 1'h0;
    else if (_012_) wdata[21] <= data_in[21];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[22] <= 1'h0;
    else if (_012_) wdata[22] <= data_in[22];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[23] <= 1'h0;
    else if (_012_) wdata[23] <= data_in[23];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[24] <= 1'h0;
    else if (_012_) wdata[24] <= data_in[24];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[25] <= 1'h0;
    else if (_012_) wdata[25] <= data_in[25];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[26] <= 1'h0;
    else if (_012_) wdata[26] <= data_in[26];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[27] <= 1'h0;
    else if (_012_) wdata[27] <= data_in[27];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[28] <= 1'h0;
    else if (_012_) wdata[28] <= data_in[28];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[29] <= 1'h0;
    else if (_012_) wdata[29] <= data_in[29];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[30] <= 1'h0;
    else if (_012_) wdata[30] <= data_in[30];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wdata[31] <= 1'h0;
    else if (_012_) wdata[31] <= data_in[31];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wstrb[0] <= 1'h0;
    else if (_012_) wstrb[0] <= strb_in[0];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wstrb[1] <= 1'h0;
    else if (_012_) wstrb[1] <= strb_in[1];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wstrb[2] <= 1'h0;
    else if (_012_) wstrb[2] <= strb_in[2];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wstrb[3] <= 1'h0;
    else if (_012_) wstrb[3] <= strb_in[3];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wvalid <= 1'h0;
    else if (_014_) wvalid <= _059_;
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) bready <= 1'h0;
    else if (_015_) bready <= _055_;
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[0] <= 1'h0;
    else if (_016_) state[0] <= _051_[0];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state[1] <= 1'h0;
    else if (_016_) state[1] <= _051_[1];
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) aw_done <= 1'h0;
    else if (_017_) aw_done <= _047_;
  (* src = "axi4_master_write.v:48.5-121.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) w_done <= 1'h0;
    else if (_018_) w_done <= _043_;
  assign _019_ = ~state[0];
  assign _020_ = ~state[1];
  assign _065_[0] = _042_[1] | _050_[0];
  assign _000_ = _034_[0] | _021_;
  assign _001_ = _065_[0] | _050_[1];
  assign _011_ = _000_ & _001_;
  assign _012_ = write_req & _042_[1];
  assign _002_ = write_req | _022_;
  assign _023_ = _019_ |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20" *)  state[1];
  assign _003_ = aw_hs | _023_;
  assign _036_ = _019_ |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20" *)  _020_;
  assign _021_ = state[0] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20" *)  _020_;
  assign _024_ = _002_ & _003_;
  assign _013_ = _024_ & _004_;
  assign _005_ = w_hs | _023_;
  assign _025_ = _002_ & _004_;
  assign _014_ = _025_ & _005_;
  assign _006_ = _035_[0] | _023_;
  assign _007_ = _042_[0] | _050_[1];
  assign _026_ = _000_ & _006_;
  assign _015_ = _026_ & _007_;
  assign _027_[0] = _042_[0] | _050_[0];
  assign _027_[1] = _050_[1] | _042_[1];
  assign _008_ = _027_[0] | _027_[1];
  assign _028_[0] = _000_ & _002_;
  assign _028_[1] = _006_ & _008_;
  assign _016_ = _028_[0] & _028_[1];
  assign _029_ = aw_hs | _035_[0];
  assign _009_ = _029_ | _023_;
  assign _017_ = _004_ & _009_;
  assign _030_ = w_hs | _035_[0];
  assign _010_ = _030_ | _023_;
  assign _018_ = _004_ & _010_;
  assign _031_[1] = _049_[5] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _049_[7];
  assign _052_[1] = _049_[3] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _031_[1];
  assign _032_[1] = _049_[4] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _049_[6];
  assign _052_[0] = _049_[3] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _032_[1];
  assign _033_[0] = _050_[0] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _050_[1];
  assign _004_ = _042_[0] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _042_[1];
  assign _067_ = _033_[0] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _004_;
  assign _056_ = _054_[0] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _049_[5];
  assign _060_ = _058_[0] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _049_[6];
  assign _064_ = _062_[0] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _049_[6];
  assign _022_ = state[0] |(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20" *)  state[1];
  assign _042_[0] = ~(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20" *) _023_;
  assign _050_[0] = ~(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20" *) _036_;
  assign _050_[1] = ~(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20" *) _021_;
  assign _042_[1] = ~(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20" *) _022_;
  assign aw_hs = awvalid &(* src = "axi4_master_write.v:45.18-45.36" *)  awready;
  assign w_hs = wvalid &(* src = "axi4_master_write.v:46.18-46.35" *)  wready;
  assign _037_ = aw_done |(* src = "axi4_master_write.v:97.26-97.42" *)  aw_hs;
  assign _038_ = w_done |(* src = "axi4_master_write.v:97.48-97.62" *)  w_hs;
  assign _035_[0] = _037_ &(* src = "axi4_master_write.v:97.25-97.63" *)  _038_;
  assign _034_[0] = bvalid &(* src = "axi4_master_write.v:106.25-106.41" *)  bready;
  assign _039_ = w_hs ? (* src = "axi4_master_write.v:88.25-88.29|axi4_master_write.v:88.21-91.24" *) 1'h1 : 1'hx;
  assign _040_[0] = _035_[0] ? (* src = "axi4_master_write.v:97.25-97.63|axi4_master_write.v:97.21-102.24" *) 1'h0 : _039_;
  assign _044_ = aw_hs ? (* src = "axi4_master_write.v:83.25-83.30|axi4_master_write.v:83.21-86.24" *) 1'h1 : 1'hx;
  assign _045_[0] = _035_[0] ? (* src = "axi4_master_write.v:97.25-97.63|axi4_master_write.v:97.21-102.24" *) 1'h0 : _044_;
  assign _048_[3] = _034_[0] ? (* src = "axi4_master_write.v:106.25-106.41|axi4_master_write.v:106.21-110.24" *) 1'h1 : 1'hx;
  assign _048_[4] = _035_[0] ? (* src = "axi4_master_write.v:97.25-97.63|axi4_master_write.v:97.21-102.24" *) 1'h0 : 1'hx;
  assign _048_[5] = _035_[0] ? (* src = "axi4_master_write.v:97.25-97.63|axi4_master_write.v:97.21-102.24" *) 1'h1 : 1'hx;
  assign _048_[6] = write_req ? (* src = "axi4_master_write.v:68.25-68.34|axi4_master_write.v:68.21-76.24" *) 1'h1 : 1'hx;
  assign _048_[7] = write_req ? (* src = "axi4_master_write.v:68.25-68.34|axi4_master_write.v:68.21-76.24" *) 1'h0 : 1'hx;
  assign _053_[0] = _034_[0] ? (* src = "axi4_master_write.v:106.25-106.41|axi4_master_write.v:106.21-110.24" *) 1'h0 : 1'hx;
  assign _057_[0] = w_hs ? (* src = "axi4_master_write.v:88.25-88.29|axi4_master_write.v:88.21-91.24" *) 1'h0 : 1'hx;
  assign _061_[0] = aw_hs ? (* src = "axi4_master_write.v:83.25-83.30|axi4_master_write.v:83.21-86.24" *) 1'h0 : 1'hx;
  assign _043_ = _004_ ? (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _041_[0] : 1'hx;
  assign _047_ = _004_ ? (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _046_[0] : 1'hx;
  assign _051_[0] = _067_ ? (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _052_[0] : 1'hx;
  assign _051_[1] = _067_ ? (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _052_[1] : 1'hx;
  assign _055_ = _007_ ? (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _056_ : 1'hx;
  assign _059_ = _004_ ? (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _060_ : 1'hx;
  assign _063_ = _004_ ? (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _064_ : 1'hx;
  assign _066_ = _001_ ? (* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _049_[3] : 1'hx;
  assign _041_[0] = _040_[0] &(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _042_[0];
  assign _046_[0] = _045_[0] &(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _042_[0];
  assign _049_[7] = _048_[7] &(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _042_[1];
  assign _049_[4] = _048_[4] &(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _042_[0];
  assign _049_[5] = _048_[5] &(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _042_[0];
  assign _054_[0] = _053_[0] &(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _050_[1];
  assign _058_[0] = _057_[0] &(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _042_[0];
  assign _049_[6] = _048_[6] &(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _042_[1];
  assign _062_[0] = _061_[0] &(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _042_[0];
  assign _049_[3] = _048_[3] &(* src = "axi4_master_write.v:0.0-0.0|axi4_master_write.v:61.13-119.20|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _050_[1];
  assign _031_[0] = _049_[3];
  assign _032_[0] = _049_[3];
  assign _033_[1] = _004_;
  assign _034_[1] = _021_;
  assign _035_[1] = _023_;
  assign _040_[1] = 1'h0;
  assign _041_[1] = 1'h0;
  assign _045_[1] = 1'h0;
  assign _046_[1] = 1'h0;
  assign _048_[2:0] = { _048_[3], 2'h0 };
  assign _049_[2:0] = { _049_[3], 2'h0 };
  assign _050_[3:2] = _042_;
  assign _053_[1] = _048_[5];
  assign _054_[1] = _049_[5];
  assign _057_[1] = _048_[6];
  assign _058_[1] = _049_[6];
  assign _061_[1] = _048_[6];
  assign _062_[1] = _049_[6];
  assign _065_[1] = _050_[1];
endmodule
