/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* src = "icg.v:1.1-19.10" *)
module icg(clk, en, gclk);
  (* src = "icg.v:2.17-2.20" *)
  input clk;
  wire clk;
  (* src = "icg.v:3.17-3.19" *)
  input en;
  wire en;
  (* src = "icg.v:4.17-4.21" *)
  output gclk;
  wire gclk;
  (* src = "icg.v:12.11-12.15" *)
  wire _0_;
  (* src = "icg.v:7.6-7.16" *)
  wire en_latched;
  INVX1 _1_ (
    .A(clk),
    .Y(_0_)
  );
  AND2X1 _2_ (
    .A(clk),
    .B(en_latched),
    .Y(gclk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "icg.v:10.7-14.2" *)
  LATCH u_latch (
    .CLK(_0_),
    .D(en),
    .Q(en_latched)
  );
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "register_bank.v:3.1-31.10" *)
module register_bank(clk, rst_n, write_en, data_in, data_out, gclk);
  (* src = "register_bank.v:7.16-7.19" *)
  input clk;
  wire clk;
  (* src = "register_bank.v:8.17-8.22" *)
  input rst_n;
  wire rst_n;
  (* src = "register_bank.v:9.16-9.24" *)
  input write_en;
  wire write_en;
  (* src = "register_bank.v:10.34-10.41" *)
  input [31:0] data_in;
  wire [31:0] data_in;
  (* src = "register_bank.v:11.33-11.41" *)
  output [31:0] data_out;
  wire [31:0] data_out;
  (* src = "register_bank.v:12.17-12.21" *)
  output gclk;
  wire gclk;
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _00_ (
    .CLK(gclk),
    .D(data_in[13]),
    .Q(data_out[13]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _01_ (
    .CLK(gclk),
    .D(data_in[14]),
    .Q(data_out[14]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _02_ (
    .CLK(gclk),
    .D(data_in[15]),
    .Q(data_out[15]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _03_ (
    .CLK(gclk),
    .D(data_in[16]),
    .Q(data_out[16]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _04_ (
    .CLK(gclk),
    .D(data_in[17]),
    .Q(data_out[17]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _05_ (
    .CLK(gclk),
    .D(data_in[18]),
    .Q(data_out[18]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _06_ (
    .CLK(gclk),
    .D(data_in[19]),
    .Q(data_out[19]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _07_ (
    .CLK(gclk),
    .D(data_in[20]),
    .Q(data_out[20]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _08_ (
    .CLK(gclk),
    .D(data_in[21]),
    .Q(data_out[21]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _09_ (
    .CLK(gclk),
    .D(data_in[22]),
    .Q(data_out[22]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _10_ (
    .CLK(gclk),
    .D(data_in[23]),
    .Q(data_out[23]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _11_ (
    .CLK(gclk),
    .D(data_in[24]),
    .Q(data_out[24]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _12_ (
    .CLK(gclk),
    .D(data_in[25]),
    .Q(data_out[25]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _13_ (
    .CLK(gclk),
    .D(data_in[26]),
    .Q(data_out[26]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _14_ (
    .CLK(gclk),
    .D(data_in[27]),
    .Q(data_out[27]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _15_ (
    .CLK(gclk),
    .D(data_in[28]),
    .Q(data_out[28]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _16_ (
    .CLK(gclk),
    .D(data_in[29]),
    .Q(data_out[29]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _17_ (
    .CLK(gclk),
    .D(data_in[30]),
    .Q(data_out[30]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _18_ (
    .CLK(gclk),
    .D(data_in[31]),
    .Q(data_out[31]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _19_ (
    .CLK(gclk),
    .D(data_in[0]),
    .Q(data_out[0]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _20_ (
    .CLK(gclk),
    .D(data_in[1]),
    .Q(data_out[1]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _21_ (
    .CLK(gclk),
    .D(data_in[2]),
    .Q(data_out[2]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _22_ (
    .CLK(gclk),
    .D(data_in[3]),
    .Q(data_out[3]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _23_ (
    .CLK(gclk),
    .D(data_in[4]),
    .Q(data_out[4]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _24_ (
    .CLK(gclk),
    .D(data_in[5]),
    .Q(data_out[5]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _25_ (
    .CLK(gclk),
    .D(data_in[6]),
    .Q(data_out[6]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _26_ (
    .CLK(gclk),
    .D(data_in[7]),
    .Q(data_out[7]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _27_ (
    .CLK(gclk),
    .D(data_in[8]),
    .Q(data_out[8]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _28_ (
    .CLK(gclk),
    .D(data_in[9]),
    .Q(data_out[9]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _29_ (
    .CLK(gclk),
    .D(data_in[10]),
    .Q(data_out[10]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _30_ (
    .CLK(gclk),
    .D(data_in[11]),
    .Q(data_out[11]),
    .R(rst_n),
    .S(1'h1)
  );
  (* src = "register_bank.v:23.1-30.4" *)
  DFFSR _31_ (
    .CLK(gclk),
    .D(data_in[12]),
    .Q(data_out[12]),
    .R(rst_n),
    .S(1'h1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "register_bank.v:16.5-21.2" *)
  icg u_icg (
    .clk(clk),
    .en(write_en),
    .gclk(gclk)
  );
endmodule
