/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module reset_sync(dst_clk, rst_n, sync_rst_n);
  input dst_clk;
  wire dst_clk;
  input rst_n;
  wire rst_n;
  reg sync_ff1;
  reg sync_ff2;
  output sync_rst_n;
  wire sync_rst_n;
  always @(posedge dst_clk, negedge rst_n)
    if (!rst_n) sync_ff2 <= 1'h0;
    else sync_ff2 <= sync_ff1;
  always @(posedge dst_clk, negedge rst_n)
    if (!rst_n) sync_ff1 <= 1'h0;
    else sync_ff1 <= 1'h1;
  assign sync_rst_n = sync_ff2;
endmodule

module reset_tree(cpu_clk, adc_clk, uart_clk, raw_rst_n, cpu_rst_n, adc_rst_n, uart_rst_n);
  input adc_clk;
  wire adc_clk;
  output adc_rst_n;
  wire adc_rst_n;
  input cpu_clk;
  wire cpu_clk;
  output cpu_rst_n;
  wire cpu_rst_n;
  input raw_rst_n;
  wire raw_rst_n;
  input uart_clk;
  wire uart_clk;
  output uart_rst_n;
  wire uart_rst_n;
  reset_sync adc_sync (
    .dst_clk(adc_clk),
    .rst_n(raw_rst_n),
    .sync_rst_n(adc_rst_n)
  );
  reset_sync cpu_sync (
    .dst_clk(cpu_clk),
    .rst_n(raw_rst_n),
    .sync_rst_n(cpu_rst_n)
  );
  reset_sync uart_sync (
    .dst_clk(uart_clk),
    .rst_n(raw_rst_n),
    .sync_rst_n(uart_rst_n)
  );
endmodule
