/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module uart_tx(clk, rst_n, tx_start, tx_data, tx, tx_busy);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire [15:0] baud_counter;
  wire [3:0] bit_counter;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  output tx;
  wire tx;
  output tx_busy;
  wire tx_busy;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  wire [9:0] tx_shift_reg;
  input tx_start;
  wire tx_start;
  sky130_fd_sc_hd__clkinv_1 _108_ (
    .A(tx_busy),
    .Y(_082_)
  );
  sky130_fd_sc_hd__clkinv_1 _109_ (
    .A(baud_counter[14]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__clkinv_1 _110_ (
    .A(baud_counter[13]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _111_ (
    .A(tx_start),
    .SLEEP(tx_busy),
    .X(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _112_ (
    .A(_082_),
    .B(tx_start),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor4_1 _113_ (
    .A(baud_counter[11]),
    .B(baud_counter[10]),
    .C(baud_counter[9]),
    .D(baud_counter[8]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nor4_1 _114_ (
    .A(baud_counter[15]),
    .B(baud_counter[14]),
    .C(baud_counter[13]),
    .D(baud_counter[12]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor4bb_1 _115_ (
    .A(baud_counter[2]),
    .B(baud_counter[1]),
    .C_N(baud_counter[0]),
    .D_N(baud_counter[3]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor4_1 _116_ (
    .A(baud_counter[7]),
    .B(baud_counter[6]),
    .C(baud_counter[5]),
    .D(baud_counter[4]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand4_1 _117_ (
    .A(_087_),
    .B(_088_),
    .C(_089_),
    .D(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _118_ (
    .A(bit_counter[0]),
    .SLEEP(bit_counter[1]),
    .X(_092_)
  );
  sky130_fd_sc_hd__nand3b_1 _119_ (
    .A_N(bit_counter[2]),
    .B(_092_),
    .C(bit_counter[3]),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor4b_1 _120_ (
    .A(baud_counter[7]),
    .B(baud_counter[6]),
    .C(baud_counter[1]),
    .D_N(baud_counter[0]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor4_1 _121_ (
    .A(baud_counter[11]),
    .B(baud_counter[10]),
    .C(baud_counter[5]),
    .D(baud_counter[4]),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand4b_1 _122_ (
    .A_N(baud_counter[2]),
    .B(_094_),
    .C(_095_),
    .D(baud_counter[3]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor3_1 _123_ (
    .A(baud_counter[15]),
    .B(baud_counter[9]),
    .C(baud_counter[8]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor3_1 _124_ (
    .A(baud_counter[14]),
    .B(baud_counter[13]),
    .C(baud_counter[12]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _125_ (
    .A(_097_),
    .B(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o21ai_0 _126_ (
    .A1(_091_),
    .A2(_093_),
    .B1(tx_busy),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21boi_0 _127_ (
    .A1(_086_),
    .A2(_100_),
    .B1_N(rst_n),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _128_ (
    .A(_082_),
    .B(_091_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a21oi_1 _129_ (
    .A1(tx),
    .A2(_086_),
    .B1(_101_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__or3b_1 _130_ (
    .A(_082_),
    .B(_091_),
    .C_N(_093_),
    .X(_103_)
  );
  sky130_fd_sc_hd__nor2_1 _131_ (
    .A(tx_shift_reg[1]),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nor4b_1 _132_ (
    .A(_082_),
    .B(_096_),
    .C(_099_),
    .D_N(_093_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o21ai_0 _133_ (
    .A1(_102_),
    .A2(_104_),
    .B1(rst_n),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _134_ (
    .A(rst_n),
    .B(_086_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__xnor2_1 _135_ (
    .A(tx_busy),
    .B(baud_counter[0]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _136_ (
    .A(_106_),
    .B(_107_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__and3_1 _137_ (
    .A(tx_busy),
    .B(baud_counter[1]),
    .C(baud_counter[0]),
    .X(_030_)
  );
  sky130_fd_sc_hd__a21oi_1 _138_ (
    .A1(tx_busy),
    .A2(baud_counter[0]),
    .B1(baud_counter[1]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor4_1 _139_ (
    .A(_101_),
    .B(_106_),
    .C(_030_),
    .D(_031_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__and4_1 _140_ (
    .A(tx_busy),
    .B(baud_counter[2]),
    .C(baud_counter[1]),
    .D(baud_counter[0]),
    .X(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _141_ (
    .A(baud_counter[2]),
    .B(_030_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor3_1 _142_ (
    .A(_106_),
    .B(_032_),
    .C(_033_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__and2_0 _143_ (
    .A(baud_counter[3]),
    .B(_032_),
    .X(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _144_ (
    .A(baud_counter[3]),
    .B(_032_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor4_1 _145_ (
    .A(_101_),
    .B(_106_),
    .C(_034_),
    .D(_035_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _146_ (
    .A(baud_counter[4]),
    .B(_034_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor2_1 _147_ (
    .A(baud_counter[4]),
    .B(_034_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor3b_1 _148_ (
    .A(_037_),
    .B(_106_),
    .C_N(_036_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xor2_1 _149_ (
    .A(baud_counter[5]),
    .B(_036_),
    .X(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _150_ (
    .A(_106_),
    .B(_038_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__and2_0 _151_ (
    .A(baud_counter[5]),
    .B(baud_counter[4]),
    .X(_039_)
  );
  sky130_fd_sc_hd__and4_1 _152_ (
    .A(baud_counter[6]),
    .B(baud_counter[3]),
    .C(_032_),
    .D(_039_),
    .X(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _153_ (
    .A1(_034_),
    .A2(_039_),
    .B1(baud_counter[6]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor3_1 _154_ (
    .A(_106_),
    .B(_040_),
    .C(_041_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _155_ (
    .A(baud_counter[7]),
    .B(_040_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor2_1 _156_ (
    .A(_106_),
    .B(_042_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__and3_1 _157_ (
    .A(baud_counter[8]),
    .B(baud_counter[7]),
    .C(_040_),
    .X(_043_)
  );
  sky130_fd_sc_hd__a21oi_1 _158_ (
    .A1(baud_counter[7]),
    .A2(_040_),
    .B1(baud_counter[8]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor3_1 _159_ (
    .A(_106_),
    .B(_043_),
    .C(_044_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__and4_1 _160_ (
    .A(baud_counter[9]),
    .B(baud_counter[8]),
    .C(baud_counter[7]),
    .D(_040_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _161_ (
    .A(baud_counter[9]),
    .B(_043_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor3_1 _162_ (
    .A(_106_),
    .B(_045_),
    .C(_046_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__and2_0 _163_ (
    .A(baud_counter[10]),
    .B(_045_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _164_ (
    .A(baud_counter[10]),
    .B(_045_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor3_1 _165_ (
    .A(_106_),
    .B(_047_),
    .C(_048_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _166_ (
    .A(baud_counter[11]),
    .B(_047_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _167_ (
    .A(_106_),
    .B(_049_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__and4_1 _168_ (
    .A(baud_counter[12]),
    .B(baud_counter[11]),
    .C(baud_counter[10]),
    .D(_045_),
    .X(_050_)
  );
  sky130_fd_sc_hd__nand4_1 _169_ (
    .A(baud_counter[12]),
    .B(baud_counter[11]),
    .C(baud_counter[10]),
    .D(_045_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a21oi_1 _170_ (
    .A1(baud_counter[11]),
    .A2(_047_),
    .B1(baud_counter[12]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor3_1 _171_ (
    .A(_106_),
    .B(_050_),
    .C(_052_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a21oi_1 _172_ (
    .A1(baud_counter[13]),
    .A2(_050_),
    .B1(_106_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a21boi_0 _173_ (
    .A1(_084_),
    .A2(_051_),
    .B1_N(_053_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nor3_1 _174_ (
    .A(_083_),
    .B(_084_),
    .C(_051_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__a21oi_1 _175_ (
    .A1(baud_counter[13]),
    .A2(_050_),
    .B1(baud_counter[14]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor3_1 _176_ (
    .A(_106_),
    .B(_054_),
    .C(_055_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__o31ai_1 _177_ (
    .A1(_083_),
    .A2(_084_),
    .A3(_051_),
    .B1(baud_counter[15]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__or4_1 _178_ (
    .A(baud_counter[15]),
    .B(_083_),
    .C(_084_),
    .D(_051_),
    .X(_057_)
  );
  sky130_fd_sc_hd__a21oi_1 _179_ (
    .A1(_056_),
    .A2(_057_),
    .B1(_106_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _180_ (
    .A(bit_counter[0]),
    .B(_101_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor2_1 _181_ (
    .A(_106_),
    .B(_058_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__o21ai_0 _182_ (
    .A1(bit_counter[0]),
    .A2(_103_),
    .B1(_101_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(bit_counter[1]),
    .B(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _184_ (
    .A(_092_),
    .B(_105_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a21oi_1 _185_ (
    .A1(_060_),
    .A2(_061_),
    .B1(_106_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a31oi_1 _186_ (
    .A1(bit_counter[1]),
    .A2(bit_counter[0]),
    .A3(_101_),
    .B1(bit_counter[2]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__and3_1 _187_ (
    .A(bit_counter[2]),
    .B(bit_counter[1]),
    .C(bit_counter[0]),
    .X(_063_)
  );
  sky130_fd_sc_hd__a211oi_1 _188_ (
    .A1(_101_),
    .A2(_063_),
    .B1(_062_),
    .C1(_106_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21o_1 _189_ (
    .A1(bit_counter[3]),
    .A2(_063_),
    .B1(_103_),
    .X(_064_)
  );
  sky130_fd_sc_hd__a21oi_1 _190_ (
    .A1(_105_),
    .A2(_063_),
    .B1(bit_counter[3]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a211oi_1 _191_ (
    .A1(_101_),
    .A2(_064_),
    .B1(_065_),
    .C1(_106_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand3_1 _192_ (
    .A(tx_shift_reg[1]),
    .B(_086_),
    .C(_103_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a22oi_1 _193_ (
    .A1(tx_data[0]),
    .A2(_085_),
    .B1(_105_),
    .B2(tx_shift_reg[2]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand3_1 _194_ (
    .A(rst_n),
    .B(_066_),
    .C(_067_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand3_1 _195_ (
    .A(tx_shift_reg[2]),
    .B(_086_),
    .C(_103_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a22oi_1 _196_ (
    .A1(tx_data[1]),
    .A2(_085_),
    .B1(_105_),
    .B2(tx_shift_reg[3]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand3_1 _197_ (
    .A(rst_n),
    .B(_068_),
    .C(_069_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand3_1 _198_ (
    .A(tx_shift_reg[3]),
    .B(_086_),
    .C(_103_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a22oi_1 _199_ (
    .A1(tx_data[2]),
    .A2(_085_),
    .B1(_105_),
    .B2(tx_shift_reg[4]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand3_1 _200_ (
    .A(rst_n),
    .B(_070_),
    .C(_071_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand3_1 _201_ (
    .A(tx_shift_reg[4]),
    .B(_086_),
    .C(_103_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a22oi_1 _202_ (
    .A1(tx_data[3]),
    .A2(_085_),
    .B1(_105_),
    .B2(tx_shift_reg[5]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand3_1 _203_ (
    .A(rst_n),
    .B(_072_),
    .C(_073_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand3_1 _204_ (
    .A(tx_shift_reg[5]),
    .B(_086_),
    .C(_103_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__a22oi_1 _205_ (
    .A1(tx_data[4]),
    .A2(_085_),
    .B1(_105_),
    .B2(tx_shift_reg[6]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand3_1 _206_ (
    .A(rst_n),
    .B(_074_),
    .C(_075_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand3_1 _207_ (
    .A(tx_shift_reg[6]),
    .B(_086_),
    .C(_103_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a22oi_1 _208_ (
    .A1(tx_data[5]),
    .A2(_085_),
    .B1(_105_),
    .B2(tx_shift_reg[7]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand3_1 _209_ (
    .A(rst_n),
    .B(_076_),
    .C(_077_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand3_1 _210_ (
    .A(tx_shift_reg[7]),
    .B(_086_),
    .C(_103_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a22oi_1 _211_ (
    .A1(tx_data[6]),
    .A2(_085_),
    .B1(_105_),
    .B2(tx_shift_reg[8]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand3_1 _212_ (
    .A(rst_n),
    .B(_078_),
    .C(_079_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand3_1 _213_ (
    .A(tx_shift_reg[8]),
    .B(_086_),
    .C(_103_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(tx_data[7]),
    .B(_085_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand4_1 _215_ (
    .A(rst_n),
    .B(_103_),
    .C(_080_),
    .D(_081_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__dfxtp_1 _216_ (
    .CLK(clk),
    .D(_000_),
    .Q(tx_busy)
  );
  sky130_fd_sc_hd__dfxtp_1 _217_ (
    .CLK(clk),
    .D(_001_),
    .Q(tx)
  );
  sky130_fd_sc_hd__dfxtp_1 _218_ (
    .CLK(clk),
    .D(_002_),
    .Q(baud_counter[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _219_ (
    .CLK(clk),
    .D(_003_),
    .Q(baud_counter[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _220_ (
    .CLK(clk),
    .D(_004_),
    .Q(baud_counter[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _221_ (
    .CLK(clk),
    .D(_005_),
    .Q(baud_counter[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _222_ (
    .CLK(clk),
    .D(_006_),
    .Q(baud_counter[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _223_ (
    .CLK(clk),
    .D(_007_),
    .Q(baud_counter[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _224_ (
    .CLK(clk),
    .D(_008_),
    .Q(baud_counter[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _225_ (
    .CLK(clk),
    .D(_009_),
    .Q(baud_counter[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _226_ (
    .CLK(clk),
    .D(_010_),
    .Q(baud_counter[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _227_ (
    .CLK(clk),
    .D(_011_),
    .Q(baud_counter[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _228_ (
    .CLK(clk),
    .D(_012_),
    .Q(baud_counter[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _229_ (
    .CLK(clk),
    .D(_013_),
    .Q(baud_counter[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _230_ (
    .CLK(clk),
    .D(_014_),
    .Q(baud_counter[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _231_ (
    .CLK(clk),
    .D(_015_),
    .Q(baud_counter[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _232_ (
    .CLK(clk),
    .D(_016_),
    .Q(baud_counter[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _233_ (
    .CLK(clk),
    .D(_017_),
    .Q(baud_counter[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _234_ (
    .CLK(clk),
    .D(_018_),
    .Q(bit_counter[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _235_ (
    .CLK(clk),
    .D(_019_),
    .Q(bit_counter[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _236_ (
    .CLK(clk),
    .D(_020_),
    .Q(bit_counter[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _237_ (
    .CLK(clk),
    .D(_021_),
    .Q(bit_counter[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _238_ (
    .CLK(clk),
    .D(_022_),
    .Q(tx_shift_reg[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _239_ (
    .CLK(clk),
    .D(_023_),
    .Q(tx_shift_reg[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _240_ (
    .CLK(clk),
    .D(_024_),
    .Q(tx_shift_reg[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _241_ (
    .CLK(clk),
    .D(_025_),
    .Q(tx_shift_reg[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _242_ (
    .CLK(clk),
    .D(_026_),
    .Q(tx_shift_reg[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _243_ (
    .CLK(clk),
    .D(_027_),
    .Q(tx_shift_reg[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _244_ (
    .CLK(clk),
    .D(_028_),
    .Q(tx_shift_reg[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _245_ (
    .CLK(clk),
    .D(_029_),
    .Q(tx_shift_reg[8])
  );
  assign tx_shift_reg[9] = 1'h1;
endmodule
